<h1>Criação de Vetores</h1>

In [4]:
import numpy as np

array = [ i for i in range(1,6)]
array2 = [ i for i in range(6,11)]

vetor1 = np.array(array) # vetor

vetor2 = np.array([array, array2]) # matriz 2x5

vetor3 = np.random.randn(2, 3) #números aleatórios uniformes, 2x3

vetor4 = np.random.rand(2, 3) # números aleatórios entre 0 e 1, 2x3

display(vetor4)

array([[0.77674842, 0.73886538, 0.63391625],
       [0.45536796, 0.0263548 , 0.91405635]])

In [7]:
zeros = np.zeros(5) # vetor 1x5 de zeros

zeros2 = np.zeros((2, 3)) # matriz 3x3 de zeros

ones = np.ones((5, 4))

#Ambos tem o mesmo funcionamento e podem ser usados com _like, para preencher um array existente

ones2 = np.ones_like(vetor2) # vetor2 é 2x5, saída 2x5

print(ones2)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [6]:
range1 = np.arange(15) # 0 a 14

print(range1)

range2 = np.arange(1,16) #1 a 15

print(range2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [9]:
full = np.full((5, 5), 15 ) # cria ixj preenchida com o valor dado

ex = np.empty((3, 5))

full2 = np.full_like(ex, 19) # preenche o array dado com o valor

print(full2)

[[19. 19. 19. 19. 19.]
 [19. 19. 19. 19. 19.]
 [19. 19. 19. 19. 19.]]


In [15]:
identidade = np.eye(5) # qualquer formato

identidade2 = np.identity(4) # apenas matriz quadrada

# ambas criam matrizes identidade 
print(identidade)
print(identidade2)
print('\n')

identidade = np.eye(5, 4)

print(identidade)

try:
    identidade2 = np.identity(5, 4)
except:
    print('Apenas matriz quadrada!')



[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
Apenas matriz quadrada!


<h1>Operações com Vetores</h1>

In [17]:
import numpy as np

arr = np.array([[1., 2., 3.], [4., 5., 6.]])

print(arr * 2)
print(arr * arr)
print(arr - arr)
print( 1 / arr)
print( arr ** 0.5)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [19]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

arr3 = arr > arr2

print(arr3)

[[ True False  True]
 [False  True False]]


In [24]:
arr = np.arange(10)

print(arr)
print(arr[5:8])

arr[5:8] = 100
print(arr)

fatia = arr[1:3]
fatia[:] = 700

print(arr)

#NUMPY NÂO COPIA, A VARIAVEL É POR REFERENCIA

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[  0   1   2   3   4 100 100 100   8   9]
[  0 700 700   3   4 100 100 100   8   9]


In [27]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr2)
print('\n')
print(arr2[1])
print('\n')
print(arr2[1][1])
print('\n')
print(arr2[1, 1]) #convenção para arrays de mts dimensões
print('\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[4 5 6]


5






In [32]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr3d)
print('\n')
print(arr3d[0])
print('\n')
print(arr3d[1, 0])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[[1 2 3]
 [4 5 6]]


[7 8 9]


In [46]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

print(arr2d)
print('\n')
print(arr2d[:2]) #duas primeiras linhas
print('\n')
print(arr2d[:2, 1:]) # os 2 últimos das duas primeiras linhas
print('\n')
print(arr2d[1, :2]) # 2 primeiros da segunda linha
print('\n')
print(arr2d[:2, 2]) # os últimos das duas primeiras linhas
print('\n')
print(arr2d[:, 1]) # segunda coluna

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 2 3]
 [4 5 6]]


[[2 3]
 [5 6]]


[4 5]


[3 6]


[2 5 8]


<h1>Vetores aleatórios</h1>

In [1]:
import numpy as np 

array1 = np.random.uniform(1, 101, 100) # 100 aleatórios uniformes entre 1 e 100

array2 = np.random.normal(0, 5, 100) # distribuição normal de centro 0 e desvio 5, 100 números

array3 = np.random.rand(5,5) # Números aleatórios no formato 5x5 entre 0 e 1

array4 = np.random.randint(1, 101, size=5) # Números entre 1 e 100, no formato dado em size=

[[0.21654349 0.2798693  0.96763987 0.82771021 0.30547121]
 [0.65041374 0.24947791 0.51503395 0.9634797  0.92552971]
 [0.97486605 0.09636456 0.16275458 0.87777483 0.99178544]
 [0.67393796 0.72125033 0.31652543 0.1099942  0.62267213]
 [0.36749743 0.54966845 0.99632793 0.09572528 0.07008224]]


<h1>Aritmética e operações matriciais</h1>

In [7]:
teste1 = np.random.randint(1, 101, size=3)
teste2 = np.random.randint(1, 101, size=3)

sin = np.sin(teste1) # TRIGONOMÉTRICAS

matriz = np.random.randint(1, 101, size=(3,3))
transposta15 = np.transpose(matriz) # TRANSPOSTA

matriz2 = np.random.randint(1, 11, size=(2,2))
matriz2 = np.linalg.det(matriz2) # DETERMINANTE

matriz_teste1 = np.random.randint(1, 11, size=(3,3)) 
matriz_teste2 = np.random.randint(1, 11, size=(3,3))

produto = matriz_teste1 @ matriz_teste2 # PRODUTO DE MATRIZES

produto_interno = np.dot(teste1, teste2) # PRODUTO INTERNO DE VETORES 

produto_vetorial = np.cross(teste1, teste2) # PRODUTO VETORIAL DE VETORES

print(teste1)
print(teste2)
print(produto_interno)


[70 87 39]
[18 73  3]
7728


In [2]:
import numpy as np

n_de_pontos = 10**7

x = np.random.uniform(-1, 1, n_de_pontos)
y = np.random.uniform(-1, 1, n_de_pontos)

distancia_do_centro = x**2 + y**2
dentro_do_circulo = distancia_do_centro <= 1

pi_aproximado = 4 * np.sum(dentro_do_circulo) / n_de_pontos
print(pi_aproximado)

3.1409816
